/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Main.Form_MenuUtama;
import java.awt.Color;
import java.sql.*;
import javax.swing.*;
import controller.koneksi;
/**
 *
 * @author neubr
 */
public class Form_Login extends javax.swing.JFrame {
    Connection conn = koneksi.getKoneksi();
    ResultSet rs = null;
    PreparedStatement pst = null; 
    int xx , xy;
    
    public Form_Login() {
        initComponents();
        
        setBackground(new Color( 0, 0, 0, 0)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        custom_JPanelRounded1 = new Custom.Custom_JPanelRounded();
        lb_username = new javax.swing.JLabel();
        lb_password = new javax.swing.JLabel();
        lb_welcome1 = new javax.swing.JLabel();
        lb_show = new javax.swing.JLabel();
        lb_hide = new javax.swing.JLabel();
        custom_JPanelRounded2 = new Custom.Custom_JPanelRounded();
        lb_image = new javax.swing.JLabel();
        lb_close = new javax.swing.JLabel();
        txtUsername = new Custom.Custom_JTextFieldRounded();
        txtPassword = new Custom.Custom_JPasswordFieldRounded();
        custom_JButtonRounded1 = new Custom.Custom_JButtonRounded();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        custom_JPanelRounded1.setBackground(new java.awt.Color(255, 255, 255));
        custom_JPanelRounded1.setRoundBottomLeft(20);
        custom_JPanelRounded1.setRoundBottomRight(20);
        custom_JPanelRounded1.setRoundTopLeft(20);
        custom_JPanelRounded1.setRoundTopRight(20);
        custom_JPanelRounded1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_username.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lb_username.setForeground(new java.awt.Color(102, 102, 102));
        lb_username.setText("Username");
        custom_JPanelRounded1.add(lb_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        lb_password.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lb_password.setForeground(new java.awt.Color(102, 102, 102));
        lb_password.setText("Password");
        custom_JPanelRounded1.add(lb_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        lb_welcome1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lb_welcome1.setForeground(new java.awt.Color(102, 102, 102));
        lb_welcome1.setText("Selamat Datang");
        custom_JPanelRounded1.add(lb_welcome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        lb_show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Show Password.png"))); // NOI18N
        lb_show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_showMouseClicked(evt);
            }
        });
        custom_JPanelRounded1.add(lb_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, 40));

        lb_hide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Hide Password.png"))); // NOI18N
        custom_JPanelRounded1.add(lb_hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, 40));

        custom_JPanelRounded2.setBackground(new java.awt.Color(255, 244, 244));
        custom_JPanelRounded2.setRoundBottomRight(20);
        custom_JPanelRounded2.setRoundTopRight(20);

        lb_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Login Posko.png"))); // NOI18N

        lb_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Close.png"))); // NOI18N
        lb_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout custom_JPanelRounded2Layout = new javax.swing.GroupLayout(custom_JPanelRounded2);
        custom_JPanelRounded2.setLayout(custom_JPanelRounded2Layout);
        custom_JPanelRounded2Layout.setHorizontalGroup(
            custom_JPanelRounded2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(custom_JPanelRounded2Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(custom_JPanelRounded2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, custom_JPanelRounded2Layout.createSequentialGroup()
                        .addComponent(lb_close)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, custom_JPanelRounded2Layout.createSequentialGroup()
                        .addComponent(lb_image)
                        .addGap(57, 57, 57))))
        );
        custom_JPanelRounded2Layout.setVerticalGroup(
            custom_JPanelRounded2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, custom_JPanelRounded2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_close)
                .addGap(18, 18, 18)
                .addComponent(lb_image)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        custom_JPanelRounded1.add(custom_JPanelRounded2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 420, 400));

        txtUsername.setForeground(new java.awt.Color(102, 102, 102));
        txtUsername.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtUsername.setMargin(new java.awt.Insets(2, 6, 2, 6));
        txtUsername.setSelectionColor(new java.awt.Color(255, 204, 204));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        custom_JPanelRounded1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 260, 40));

        txtPassword.setForeground(new java.awt.Color(102, 102, 102));
        txtPassword.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtPassword.setSelectionColor(new java.awt.Color(255, 204, 204));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        custom_JPanelRounded1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 260, 40));

        custom_JButtonRounded1.setBackground(new java.awt.Color(255, 204, 204));
        custom_JButtonRounded1.setForeground(new java.awt.Color(102, 102, 102));
        custom_JButtonRounded1.setText("LOGIN");
        custom_JButtonRounded1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        custom_JButtonRounded1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custom_JButtonRounded1ActionPerformed(evt);
            }
        });
        custom_JPanelRounded1.add(custom_JButtonRounded1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 260, 40));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Hai,");
        custom_JPanelRounded1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(custom_JPanelRounded1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(custom_JPanelRounded1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
       xx = evt.getX();
       xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();
       this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void custom_JButtonRounded1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custom_JButtonRounded1ActionPerformed
//        Form_MenuUtama mn = new Form_MenuUtama();
//        mn.setVisible(true);
//        mn.revalidate();
//        
//        dispose();
    String sql = "select * from login where username=? and password=? ";
    try{
        pst = conn.prepareStatement(sql);
        pst.setString(1, txtUsername.getText());
        pst.setString(2, String.valueOf(txtPassword.getPassword()));
        rs = pst.executeQuery();
        if(rs.next()){
            JOptionPane.showMessageDialog(null, "Login Berhasil");
            new Form_MenuUtama().setVisible(true);
             this.dispose();
        }else
            JOptionPane.showMessageDialog(null, "Login Gagal");
    }catch (Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_custom_JButtonRounded1ActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void lb_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_closeMouseClicked
        dispose();
        System.exit(0);
    }//GEN-LAST:event_lb_closeMouseClicked
   private boolean passwordVisible = false;
    private void lb_showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_showMouseClicked
                                   
       if (passwordVisible) {
        // Jika sandi terlihat, sembunyikan sandi
        txtPassword.setEchoChar('\u25cf'); // Gunakan karakter bintang sebagai pengganti teks sandi
        lb_hide.setVisible(true); // Tampilkan ikon "Hide Password"
        lb_show.setVisible(false); // Sembunyikan ikon "Show Password"
        passwordVisible = false; // Perbarui status tampilan sandi
    } else {
        // Jika sandi tersembunyi, tampilkan sandi
        txtPassword.setEchoChar((char)0); // Tampilkan teks biasa tanpa enkripsi
        lb_hide.setVisible(false); // Sembunyikan ikon "Hide Password"
        lb_show.setVisible(true); // Tampilkan ikon "Show Password"
        passwordVisible = true; // Perbarui status tampilan sandi
    }
    }//GEN-LAST:event_lb_showMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Custom.Custom_JButtonRounded custom_JButtonRounded1;
    private Custom.Custom_JPanelRounded custom_JPanelRounded1;
    private Custom.Custom_JPanelRounded custom_JPanelRounded2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb_close;
    private javax.swing.JLabel lb_hide;
    private javax.swing.JLabel lb_image;
    private javax.swing.JLabel lb_password;
    private javax.swing.JLabel lb_show;
    private javax.swing.JLabel lb_username;
    private javax.swing.JLabel lb_welcome1;
    private Custom.Custom_JPasswordFieldRounded txtPassword;
    private Custom.Custom_JTextFieldRounded txtUsername;
    // End of variables declaration//GEN-END:variables
}
