/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import controller.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author neubr
 */
public class Menu_Dashboard extends javax.swing.JPanel {

    private Connection conn;
    /**
     * Creates new form Menu_Dashboard
     */
    public Menu_Dashboard() {
        initComponents();
        conn = controller.koneksi.getKoneksi();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        card_pasien = new Custom.Custom_JPanelRounded();
        lb_pasien = new javax.swing.JLabel();
        lb_iconpasien = new javax.swing.JLabel();
        lb_jumlahpasien = new javax.swing.JLabel();
        card_ambulan = new Custom.Custom_JPanelRounded();
        lb_ambulan = new javax.swing.JLabel();
        lb_iconambulan = new javax.swing.JLabel();
        lb_jumlahambulan = new javax.swing.JLabel();
        card_penerimaan = new Custom.Custom_JPanelRounded();
        lb_penerimaan = new javax.swing.JLabel();
        lb_iconpenerimaan = new javax.swing.JLabel();
        lb_jumlahpenerimaan = new javax.swing.JLabel();
        card_penanganan = new Custom.Custom_JPanelRounded();
        lb_penanganan = new javax.swing.JLabel();
        lb_iconpenanganan = new javax.swing.JLabel();
        lb_jumlahpenanganan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        custom_JTable1 = new Custom.Custom_JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1026, 658));

        card_pasien.setBackground(new java.awt.Color(255, 0, 0));
        card_pasien.setPreferredSize(new java.awt.Dimension(207, 121));
        card_pasien.setRoundBottomLeft(30);
        card_pasien.setRoundBottomRight(30);
        card_pasien.setRoundTopLeft(30);
        card_pasien.setRoundTopRight(30);

        lb_pasien.setBackground(new java.awt.Color(255, 255, 255));
        lb_pasien.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lb_pasien.setForeground(new java.awt.Color(255, 255, 255));
        lb_pasien.setText("PASIEN");

        lb_iconpasien.setBackground(new java.awt.Color(102, 102, 102));
        lb_iconpasien.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lb_iconpasien.setForeground(new java.awt.Color(255, 255, 255));
        lb_iconpasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Pasien.png"))); // NOI18N

        lb_jumlahpasien.setBackground(new java.awt.Color(102, 102, 102));
        lb_jumlahpasien.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lb_jumlahpasien.setForeground(new java.awt.Color(255, 255, 255));
        lb_jumlahpasien.setText("20");

        javax.swing.GroupLayout card_pasienLayout = new javax.swing.GroupLayout(card_pasien);
        card_pasien.setLayout(card_pasienLayout);
        card_pasienLayout.setHorizontalGroup(
            card_pasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_pasienLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(card_pasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_pasien)
                    .addComponent(lb_jumlahpasien))
                .addGap(50, 50, 50)
                .addComponent(lb_iconpasien)
                .addGap(20, 20, 20))
        );
        card_pasienLayout.setVerticalGroup(
            card_pasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_pasienLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(card_pasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_iconpasien)
                    .addGroup(card_pasienLayout.createSequentialGroup()
                        .addComponent(lb_pasien)
                        .addGap(20, 20, 20)
                        .addComponent(lb_jumlahpasien)))
                .addGap(20, 20, 20))
        );

        card_ambulan.setBackground(new java.awt.Color(255, 0, 0));
        card_ambulan.setRoundBottomLeft(30);
        card_ambulan.setRoundBottomRight(30);
        card_ambulan.setRoundTopLeft(30);
        card_ambulan.setRoundTopRight(30);

        lb_ambulan.setBackground(new java.awt.Color(255, 255, 255));
        lb_ambulan.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lb_ambulan.setForeground(new java.awt.Color(255, 255, 255));
        lb_ambulan.setText("AMBULAN");

        lb_iconambulan.setBackground(new java.awt.Color(102, 102, 102));
        lb_iconambulan.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lb_iconambulan.setForeground(new java.awt.Color(255, 255, 255));
        lb_iconambulan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Ambulan.png"))); // NOI18N

        lb_jumlahambulan.setBackground(new java.awt.Color(102, 102, 102));
        lb_jumlahambulan.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lb_jumlahambulan.setForeground(new java.awt.Color(255, 255, 255));
        lb_jumlahambulan.setText("4");

        javax.swing.GroupLayout card_ambulanLayout = new javax.swing.GroupLayout(card_ambulan);
        card_ambulan.setLayout(card_ambulanLayout);
        card_ambulanLayout.setHorizontalGroup(
            card_ambulanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_ambulanLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(card_ambulanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_ambulan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_jumlahambulan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addComponent(lb_iconambulan)
                .addGap(20, 20, 20))
        );
        card_ambulanLayout.setVerticalGroup(
            card_ambulanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_ambulanLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(card_ambulanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_iconambulan)
                    .addGroup(card_ambulanLayout.createSequentialGroup()
                        .addComponent(lb_ambulan)
                        .addGap(18, 18, 18)
                        .addComponent(lb_jumlahambulan)))
                .addGap(20, 20, 20))
        );

        card_penerimaan.setBackground(new java.awt.Color(255, 0, 0));
        card_penerimaan.setRoundBottomLeft(30);
        card_penerimaan.setRoundBottomRight(30);
        card_penerimaan.setRoundTopLeft(30);
        card_penerimaan.setRoundTopRight(30);

        lb_penerimaan.setBackground(new java.awt.Color(255, 255, 255));
        lb_penerimaan.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lb_penerimaan.setForeground(new java.awt.Color(255, 255, 255));
        lb_penerimaan.setText("PENERIMAAN");

        lb_iconpenerimaan.setBackground(new java.awt.Color(102, 102, 102));
        lb_iconpenerimaan.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lb_iconpenerimaan.setForeground(new java.awt.Color(255, 255, 255));
        lb_iconpenerimaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Penerimaan.png"))); // NOI18N

        lb_jumlahpenerimaan.setBackground(new java.awt.Color(102, 102, 102));
        lb_jumlahpenerimaan.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lb_jumlahpenerimaan.setForeground(new java.awt.Color(255, 255, 255));
        lb_jumlahpenerimaan.setText("12");

        javax.swing.GroupLayout card_penerimaanLayout = new javax.swing.GroupLayout(card_penerimaan);
        card_penerimaan.setLayout(card_penerimaanLayout);
        card_penerimaanLayout.setHorizontalGroup(
            card_penerimaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_penerimaanLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(card_penerimaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_penerimaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_jumlahpenerimaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addComponent(lb_iconpenerimaan)
                .addGap(20, 20, 20))
        );
        card_penerimaanLayout.setVerticalGroup(
            card_penerimaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_penerimaanLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(card_penerimaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_iconpenerimaan)
                    .addGroup(card_penerimaanLayout.createSequentialGroup()
                        .addComponent(lb_penerimaan)
                        .addGap(18, 18, 18)
                        .addComponent(lb_jumlahpenerimaan)))
                .addGap(20, 20, 20))
        );

        card_penanganan.setBackground(new java.awt.Color(255, 0, 0));
        card_penanganan.setRoundBottomLeft(30);
        card_penanganan.setRoundBottomRight(30);
        card_penanganan.setRoundTopLeft(30);
        card_penanganan.setRoundTopRight(30);

        lb_penanganan.setBackground(new java.awt.Color(255, 255, 255));
        lb_penanganan.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lb_penanganan.setForeground(new java.awt.Color(255, 255, 255));
        lb_penanganan.setText("PENANGANAN");

        lb_iconpenanganan.setBackground(new java.awt.Color(102, 102, 102));
        lb_iconpenanganan.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lb_iconpenanganan.setForeground(new java.awt.Color(255, 255, 255));
        lb_iconpenanganan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Penanganan.png"))); // NOI18N

        lb_jumlahpenanganan.setBackground(new java.awt.Color(102, 102, 102));
        lb_jumlahpenanganan.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lb_jumlahpenanganan.setForeground(new java.awt.Color(255, 255, 255));
        lb_jumlahpenanganan.setText("11");

        javax.swing.GroupLayout card_penangananLayout = new javax.swing.GroupLayout(card_penanganan);
        card_penanganan.setLayout(card_penangananLayout);
        card_penangananLayout.setHorizontalGroup(
            card_penangananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_penangananLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(card_penangananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_penanganan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_jumlahpenanganan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addComponent(lb_iconpenanganan)
                .addGap(20, 20, 20))
        );
        card_penangananLayout.setVerticalGroup(
            card_penangananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_penangananLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(card_penangananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_iconpenanganan)
                    .addGroup(card_penangananLayout.createSequentialGroup()
                        .addComponent(lb_penanganan)
                        .addGap(18, 18, 18)
                        .addComponent(lb_jumlahpenanganan)))
                .addGap(20, 20, 20))
        );

        custom_JTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(custom_JTable1);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Riwayat Penerimaan Pasien");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Master Data > Dashboard");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon DashboardSB.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 987, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(card_pasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(card_ambulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(card_penerimaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel2))
                                .addComponent(card_penanganan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(card_ambulan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(card_pasien, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                        .addComponent(card_penanganan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(card_penerimaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Custom.Custom_JPanelRounded card_ambulan;
    private Custom.Custom_JPanelRounded card_pasien;
    private Custom.Custom_JPanelRounded card_penanganan;
    private Custom.Custom_JPanelRounded card_penerimaan;
    private Custom.Custom_JTable custom_JTable1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_ambulan;
    private javax.swing.JLabel lb_iconambulan;
    private javax.swing.JLabel lb_iconpasien;
    private javax.swing.JLabel lb_iconpenanganan;
    private javax.swing.JLabel lb_iconpenerimaan;
    private javax.swing.JLabel lb_jumlahambulan;
    private javax.swing.JLabel lb_jumlahpasien;
    private javax.swing.JLabel lb_jumlahpenanganan;
    private javax.swing.JLabel lb_jumlahpenerimaan;
    private javax.swing.JLabel lb_pasien;
    private javax.swing.JLabel lb_penanganan;
    private javax.swing.JLabel lb_penerimaan;
    // End of variables declaration//GEN-END:variables

    
    private int jumlahPasien(){
        int totalPasien = 0;
        
        try {
            String sql = "SELECT COUNT(*) AS total FROM pasien";
            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            
            if(rs.next()){
                totalPasien = rs.getInt("total");
            }
        } catch (Exception e){
            e.printStackTrace();
        }
        return totalPasien;
    }
    
    
     private int jumlahAmbulans(){
        int totalambulans = 0;
        
        try {
            String sql = "SELECT COUNT(*) AS total FROM ambulans";
            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            
            if(rs.next()){
                totalambulans = rs.getInt("total");
            }
        } catch (Exception e){
            e.printStackTrace();
        }
        return totalambulans;
    }
     
      private int jumlahPenerimaan(){
        int totalPasien = 0;
        
        try {
            String sql = "SELECT COUNT(*) AS total FROM penerimaan";
            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            
            if(rs.next()){
                totalPasien = rs.getInt("total");
            }
        } catch (Exception e){
            e.printStackTrace();
        }
        return totalPasien;
    }
      
       private int jumlahPenanganan(){
        int totalPenanganan = 0;
        
        try {
            String sql = "SELECT COUNT(*) AS total FROM penanganan";
            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            
            if(rs.next()){
                totalPenanganan = rs.getInt("total");
            }
        } catch (Exception e){
            e.printStackTrace();
        }
        return totalPenanganan;
    }
     
    private void loadData() {
       lb_jumlahpasien.setText(String.valueOf(jumlahPasien()));
       lb_jumlahambulan.setText(String.valueOf(jumlahAmbulans()));
       lb_jumlahpenerimaan.setText(String.valueOf(jumlahPenerimaan()));
       lb_jumlahpenanganan.setText(String.valueOf(jumlahPenanganan()));
    }
}

