package Main;

import View.Menu_Dashboard;
import View.Menu_Pasien;
import View.Menu_Petugas;
import View.Menu_Ambulans;
import View.Menu_Penerimaan;
import View.Menu_Penanganan;
import View.cetak_faktur_Penerimaan;
import View.cetak_faktur_Penanganan;
import View.cetak_faktur_Pasien;
import View.cetak_faktur_Petugas;
import View.cetak_faktur_Ambulan;
import java.awt.Color;

/*
 *
 * @author neubr
 */
public class Form_MenuUtama extends javax.swing.JFrame {

    int xx, xy;

    public Form_MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_kiri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pn_btnDashboard = new javax.swing.JPanel();
        pn_line = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_dashboard = new javax.swing.JLabel();
        pn_btnPasien = new javax.swing.JPanel();
        pn_line3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btn_pasien = new javax.swing.JLabel();
        pn_btnPetugas = new javax.swing.JPanel();
        pn_line4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btn_petugas = new javax.swing.JLabel();
        pn_btnAmbulan = new javax.swing.JPanel();
        pn_line5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btn_ambulan = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pn_btnPenerimaan = new javax.swing.JPanel();
        pn_line6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btn_penerimaan = new javax.swing.JLabel();
        pn_btnPenanganan = new javax.swing.JPanel();
        pn_line7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btn_penanganan = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pn_btnlpAnggota = new javax.swing.JPanel();
        pn_line8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btn_lpPasien = new javax.swing.JLabel();
        pn_btnlpKegiatan = new javax.swing.JPanel();
        pn_line9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btn_lpPetugas = new javax.swing.JLabel();
        pn_btnlpAmbulan = new javax.swing.JPanel();
        pn_line10 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btn_lpAmbulan = new javax.swing.JLabel();
        pn_btnlpPenerimaan = new javax.swing.JPanel();
        pn_line11 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btn_lpPenerimaan = new javax.swing.JLabel();
        pn_btnlpPenanganan = new javax.swing.JPanel();
        pn_line12 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btn_lpPenanganan = new javax.swing.JLabel();
        pn_kanan = new javax.swing.JPanel();
        custom_JPanelGradient1 = new Custom.Custom_JPanelGradient();
        pn_dasar = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pn_kiri.setBackground(new java.awt.Color(255, 255, 255));
        pn_kiri.setPreferredSize(new java.awt.Dimension(300, 768));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Logo PMI Kecil.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Posko PMI");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Kota Jakarta Timur");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("MASTER DATA");

        pn_btnDashboard.setBackground(new java.awt.Color(255, 255, 255));

        pn_line.setBackground(new java.awt.Color(255, 255, 255));
        pn_line.setPreferredSize(new java.awt.Dimension(5, 36));

        javax.swing.GroupLayout pn_lineLayout = new javax.swing.GroupLayout(pn_line);
        pn_line.setLayout(pn_lineLayout);
        pn_lineLayout.setHorizontalGroup(
            pn_lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_lineLayout.setVerticalGroup(
            pn_lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon DashboardSB.png"))); // NOI18N

        btn_dashboard.setBackground(new java.awt.Color(102, 102, 102));
        btn_dashboard.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_dashboard.setForeground(new java.awt.Color(102, 102, 102));
        btn_dashboard.setText("Dashboard");
        btn_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btnDashboardLayout = new javax.swing.GroupLayout(pn_btnDashboard);
        pn_btnDashboard.setLayout(pn_btnDashboardLayout);
        pn_btnDashboardLayout.setHorizontalGroup(
            pn_btnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnDashboardLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(btn_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_btnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_btnDashboardLayout.createSequentialGroup()
                    .addComponent(pn_line, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 250, Short.MAX_VALUE)))
        );
        pn_btnDashboardLayout.setVerticalGroup(
            pn_btnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(btn_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_btnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pn_line, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_btnPasien.setBackground(new java.awt.Color(255, 255, 255));

        pn_line3.setBackground(new java.awt.Color(255, 255, 255));
        pn_line3.setPreferredSize(new java.awt.Dimension(5, 36));

        javax.swing.GroupLayout pn_line3Layout = new javax.swing.GroupLayout(pn_line3);
        pn_line3.setLayout(pn_line3Layout);
        pn_line3Layout.setHorizontalGroup(
            pn_line3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pn_line3Layout.setVerticalGroup(
            pn_line3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon PasienSB.png"))); // NOI18N

        btn_pasien.setBackground(new java.awt.Color(102, 102, 102));
        btn_pasien.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_pasien.setForeground(new java.awt.Color(102, 102, 102));
        btn_pasien.setText("Pasien");
        btn_pasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pasienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pasienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pasienMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btnPasienLayout = new javax.swing.GroupLayout(pn_btnPasien);
        pn_btnPasien.setLayout(pn_btnPasienLayout);
        pn_btnPasienLayout.setHorizontalGroup(
            pn_btnPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnPasienLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(btn_pasien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_btnPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_btnPasienLayout.createSequentialGroup()
                    .addComponent(pn_line3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 255, Short.MAX_VALUE)))
        );
        pn_btnPasienLayout.setVerticalGroup(
            pn_btnPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
            .addComponent(btn_pasien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_btnPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pn_line3, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
        );

        pn_btnPetugas.setBackground(new java.awt.Color(255, 255, 255));

        pn_line4.setBackground(new java.awt.Color(255, 255, 255));
        pn_line4.setPreferredSize(new java.awt.Dimension(5, 36));

        javax.swing.GroupLayout pn_line4Layout = new javax.swing.GroupLayout(pn_line4);
        pn_line4.setLayout(pn_line4Layout);
        pn_line4Layout.setHorizontalGroup(
            pn_line4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_line4Layout.setVerticalGroup(
            pn_line4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon PetugasSB.png"))); // NOI18N

        btn_petugas.setBackground(new java.awt.Color(102, 102, 102));
        btn_petugas.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_petugas.setForeground(new java.awt.Color(102, 102, 102));
        btn_petugas.setText("Petugas");
        btn_petugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_petugasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_petugasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_petugasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btnPetugasLayout = new javax.swing.GroupLayout(pn_btnPetugas);
        pn_btnPetugas.setLayout(pn_btnPetugasLayout);
        pn_btnPetugasLayout.setHorizontalGroup(
            pn_btnPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnPetugasLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(btn_petugas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_btnPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_btnPetugasLayout.createSequentialGroup()
                    .addComponent(pn_line4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 250, Short.MAX_VALUE)))
        );
        pn_btnPetugasLayout.setVerticalGroup(
            pn_btnPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(btn_petugas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_btnPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pn_line4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_btnAmbulan.setBackground(new java.awt.Color(255, 255, 255));

        pn_line5.setBackground(new java.awt.Color(255, 255, 255));
        pn_line5.setPreferredSize(new java.awt.Dimension(5, 36));

        javax.swing.GroupLayout pn_line5Layout = new javax.swing.GroupLayout(pn_line5);
        pn_line5.setLayout(pn_line5Layout);
        pn_line5Layout.setHorizontalGroup(
            pn_line5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_line5Layout.setVerticalGroup(
            pn_line5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon AmbulanSB.png"))); // NOI18N

        btn_ambulan.setBackground(new java.awt.Color(102, 102, 102));
        btn_ambulan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_ambulan.setForeground(new java.awt.Color(102, 102, 102));
        btn_ambulan.setText("Ambulan");
        btn_ambulan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ambulanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ambulanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ambulanMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btnAmbulanLayout = new javax.swing.GroupLayout(pn_btnAmbulan);
        pn_btnAmbulan.setLayout(pn_btnAmbulanLayout);
        pn_btnAmbulanLayout.setHorizontalGroup(
            pn_btnAmbulanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnAmbulanLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(btn_ambulan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_btnAmbulanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_btnAmbulanLayout.createSequentialGroup()
                    .addComponent(pn_line5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 250, Short.MAX_VALUE)))
        );
        pn_btnAmbulanLayout.setVerticalGroup(
            pn_btnAmbulanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(btn_ambulan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_btnAmbulanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pn_line5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("TRANSAKSI");

        pn_btnPenerimaan.setBackground(new java.awt.Color(255, 255, 255));

        pn_line6.setBackground(new java.awt.Color(255, 255, 255));
        pn_line6.setPreferredSize(new java.awt.Dimension(5, 36));

        javax.swing.GroupLayout pn_line6Layout = new javax.swing.GroupLayout(pn_line6);
        pn_line6.setLayout(pn_line6Layout);
        pn_line6Layout.setHorizontalGroup(
            pn_line6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_line6Layout.setVerticalGroup(
            pn_line6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon PenerimaanSB.png"))); // NOI18N

        btn_penerimaan.setBackground(new java.awt.Color(102, 102, 102));
        btn_penerimaan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_penerimaan.setForeground(new java.awt.Color(102, 102, 102));
        btn_penerimaan.setText("Penerimaan");
        btn_penerimaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_penerimaanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_penerimaanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_penerimaanMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btnPenerimaanLayout = new javax.swing.GroupLayout(pn_btnPenerimaan);
        pn_btnPenerimaan.setLayout(pn_btnPenerimaanLayout);
        pn_btnPenerimaanLayout.setHorizontalGroup(
            pn_btnPenerimaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnPenerimaanLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(btn_penerimaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_btnPenerimaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_btnPenerimaanLayout.createSequentialGroup()
                    .addComponent(pn_line6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 250, Short.MAX_VALUE)))
        );
        pn_btnPenerimaanLayout.setVerticalGroup(
            pn_btnPenerimaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(btn_penerimaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_btnPenerimaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pn_line6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_btnPenanganan.setBackground(new java.awt.Color(255, 255, 255));

        pn_line7.setBackground(new java.awt.Color(255, 255, 255));
        pn_line7.setPreferredSize(new java.awt.Dimension(5, 36));

        javax.swing.GroupLayout pn_line7Layout = new javax.swing.GroupLayout(pn_line7);
        pn_line7.setLayout(pn_line7Layout);
        pn_line7Layout.setHorizontalGroup(
            pn_line7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_line7Layout.setVerticalGroup(
            pn_line7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon PenangananSB.png"))); // NOI18N

        btn_penanganan.setBackground(new java.awt.Color(102, 102, 102));
        btn_penanganan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_penanganan.setForeground(new java.awt.Color(102, 102, 102));
        btn_penanganan.setText("Penanganan");
        btn_penanganan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_penangananMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_penangananMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_penangananMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btnPenangananLayout = new javax.swing.GroupLayout(pn_btnPenanganan);
        pn_btnPenanganan.setLayout(pn_btnPenangananLayout);
        pn_btnPenangananLayout.setHorizontalGroup(
            pn_btnPenangananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnPenangananLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(btn_penanganan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_btnPenangananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_btnPenangananLayout.createSequentialGroup()
                    .addComponent(pn_line7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 250, Short.MAX_VALUE)))
        );
        pn_btnPenangananLayout.setVerticalGroup(
            pn_btnPenangananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(btn_penanganan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_btnPenangananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pn_line7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("CETAK FAKTUR");

        pn_btnlpAnggota.setBackground(new java.awt.Color(255, 255, 255));

        pn_line8.setBackground(new java.awt.Color(255, 255, 255));
        pn_line8.setPreferredSize(new java.awt.Dimension(5, 36));

        javax.swing.GroupLayout pn_line8Layout = new javax.swing.GroupLayout(pn_line8);
        pn_line8.setLayout(pn_line8Layout);
        pn_line8Layout.setHorizontalGroup(
            pn_line8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_line8Layout.setVerticalGroup(
            pn_line8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon ReportSB.png"))); // NOI18N

        btn_lpPasien.setBackground(new java.awt.Color(102, 102, 102));
        btn_lpPasien.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_lpPasien.setForeground(new java.awt.Color(102, 102, 102));
        btn_lpPasien.setText("Pasien");
        btn_lpPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_lpPasienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_lpPasienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_lpPasienMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btnlpAnggotaLayout = new javax.swing.GroupLayout(pn_btnlpAnggota);
        pn_btnlpAnggota.setLayout(pn_btnlpAnggotaLayout);
        pn_btnlpAnggotaLayout.setHorizontalGroup(
            pn_btnlpAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnlpAnggotaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(btn_lpPasien, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
            .addGroup(pn_btnlpAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_btnlpAnggotaLayout.createSequentialGroup()
                    .addComponent(pn_line8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 250, Short.MAX_VALUE)))
        );
        pn_btnlpAnggotaLayout.setVerticalGroup(
            pn_btnlpAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(btn_lpPasien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_btnlpAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pn_line8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_btnlpKegiatan.setBackground(new java.awt.Color(255, 255, 255));

        pn_line9.setBackground(new java.awt.Color(255, 255, 255));
        pn_line9.setPreferredSize(new java.awt.Dimension(5, 36));

        javax.swing.GroupLayout pn_line9Layout = new javax.swing.GroupLayout(pn_line9);
        pn_line9.setLayout(pn_line9Layout);
        pn_line9Layout.setHorizontalGroup(
            pn_line9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_line9Layout.setVerticalGroup(
            pn_line9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon ReportSB.png"))); // NOI18N

        btn_lpPetugas.setBackground(new java.awt.Color(102, 102, 102));
        btn_lpPetugas.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_lpPetugas.setForeground(new java.awt.Color(102, 102, 102));
        btn_lpPetugas.setText("Petugas");
        btn_lpPetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_lpPetugasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_lpPetugasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_lpPetugasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btnlpKegiatanLayout = new javax.swing.GroupLayout(pn_btnlpKegiatan);
        pn_btnlpKegiatan.setLayout(pn_btnlpKegiatanLayout);
        pn_btnlpKegiatanLayout.setHorizontalGroup(
            pn_btnlpKegiatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnlpKegiatanLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(btn_lpPetugas, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
            .addGroup(pn_btnlpKegiatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_btnlpKegiatanLayout.createSequentialGroup()
                    .addComponent(pn_line9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 250, Short.MAX_VALUE)))
        );
        pn_btnlpKegiatanLayout.setVerticalGroup(
            pn_btnlpKegiatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(btn_lpPetugas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_btnlpKegiatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pn_line9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_btnlpAmbulan.setBackground(new java.awt.Color(255, 255, 255));

        pn_line10.setBackground(new java.awt.Color(255, 255, 255));
        pn_line10.setPreferredSize(new java.awt.Dimension(5, 36));

        javax.swing.GroupLayout pn_line10Layout = new javax.swing.GroupLayout(pn_line10);
        pn_line10.setLayout(pn_line10Layout);
        pn_line10Layout.setHorizontalGroup(
            pn_line10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_line10Layout.setVerticalGroup(
            pn_line10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon ReportSB.png"))); // NOI18N

        btn_lpAmbulan.setBackground(new java.awt.Color(102, 102, 102));
        btn_lpAmbulan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_lpAmbulan.setForeground(new java.awt.Color(102, 102, 102));
        btn_lpAmbulan.setText("Ambulan");
        btn_lpAmbulan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_lpAmbulanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_lpAmbulanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_lpAmbulanMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btnlpAmbulanLayout = new javax.swing.GroupLayout(pn_btnlpAmbulan);
        pn_btnlpAmbulan.setLayout(pn_btnlpAmbulanLayout);
        pn_btnlpAmbulanLayout.setHorizontalGroup(
            pn_btnlpAmbulanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnlpAmbulanLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(btn_lpAmbulan, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
            .addGroup(pn_btnlpAmbulanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_btnlpAmbulanLayout.createSequentialGroup()
                    .addComponent(pn_line10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 250, Short.MAX_VALUE)))
        );
        pn_btnlpAmbulanLayout.setVerticalGroup(
            pn_btnlpAmbulanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(btn_lpAmbulan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_btnlpAmbulanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pn_line10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_btnlpPenerimaan.setBackground(new java.awt.Color(255, 255, 255));

        pn_line11.setBackground(new java.awt.Color(255, 255, 255));
        pn_line11.setPreferredSize(new java.awt.Dimension(5, 36));

        javax.swing.GroupLayout pn_line11Layout = new javax.swing.GroupLayout(pn_line11);
        pn_line11.setLayout(pn_line11Layout);
        pn_line11Layout.setHorizontalGroup(
            pn_line11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_line11Layout.setVerticalGroup(
            pn_line11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon ReportSB.png"))); // NOI18N

        btn_lpPenerimaan.setBackground(new java.awt.Color(102, 102, 102));
        btn_lpPenerimaan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_lpPenerimaan.setForeground(new java.awt.Color(102, 102, 102));
        btn_lpPenerimaan.setText("Penerimaan");
        btn_lpPenerimaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_lpPenerimaanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_lpPenerimaanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_lpPenerimaanMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btnlpPenerimaanLayout = new javax.swing.GroupLayout(pn_btnlpPenerimaan);
        pn_btnlpPenerimaan.setLayout(pn_btnlpPenerimaanLayout);
        pn_btnlpPenerimaanLayout.setHorizontalGroup(
            pn_btnlpPenerimaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnlpPenerimaanLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(btn_lpPenerimaan, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
            .addGroup(pn_btnlpPenerimaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_btnlpPenerimaanLayout.createSequentialGroup()
                    .addComponent(pn_line11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 250, Short.MAX_VALUE)))
        );
        pn_btnlpPenerimaanLayout.setVerticalGroup(
            pn_btnlpPenerimaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(btn_lpPenerimaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_btnlpPenerimaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pn_line11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_btnlpPenanganan.setBackground(new java.awt.Color(255, 255, 255));

        pn_line12.setBackground(new java.awt.Color(255, 255, 255));
        pn_line12.setPreferredSize(new java.awt.Dimension(5, 36));

        javax.swing.GroupLayout pn_line12Layout = new javax.swing.GroupLayout(pn_line12);
        pn_line12.setLayout(pn_line12Layout);
        pn_line12Layout.setHorizontalGroup(
            pn_line12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_line12Layout.setVerticalGroup(
            pn_line12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon ReportSB.png"))); // NOI18N

        btn_lpPenanganan.setBackground(new java.awt.Color(102, 102, 102));
        btn_lpPenanganan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_lpPenanganan.setForeground(new java.awt.Color(102, 102, 102));
        btn_lpPenanganan.setText("Penanganan");
        btn_lpPenanganan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_lpPenangananMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_lpPenangananMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_lpPenangananMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btnlpPenangananLayout = new javax.swing.GroupLayout(pn_btnlpPenanganan);
        pn_btnlpPenanganan.setLayout(pn_btnlpPenangananLayout);
        pn_btnlpPenangananLayout.setHorizontalGroup(
            pn_btnlpPenangananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnlpPenangananLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(btn_lpPenanganan, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
            .addGroup(pn_btnlpPenangananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_btnlpPenangananLayout.createSequentialGroup()
                    .addComponent(pn_line12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 250, Short.MAX_VALUE)))
        );
        pn_btnlpPenangananLayout.setVerticalGroup(
            pn_btnlpPenangananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(btn_lpPenanganan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_btnlpPenangananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pn_line12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_kiriLayout = new javax.swing.GroupLayout(pn_kiri);
        pn_kiri.setLayout(pn_kiriLayout);
        pn_kiriLayout.setHorizontalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_btnlpPenanganan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_btnlpPenerimaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_btnlpAmbulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_btnlpKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(pn_btnlpAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pn_kiriLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(pn_btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pn_btnPasien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pn_btnPetugas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pn_btnAmbulan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addComponent(pn_btnPenerimaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pn_btnPenanganan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pn_kiriLayout.setVerticalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnAmbulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnPenerimaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnPenanganan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnlpAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnlpKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnlpAmbulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnlpPenerimaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnlpPenanganan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        getContentPane().add(pn_kiri, java.awt.BorderLayout.LINE_START);

        pn_kanan.setBackground(new java.awt.Color(255, 255, 255));
        pn_kanan.setLayout(new java.awt.BorderLayout());

        custom_JPanelGradient1.setColorEnd(new java.awt.Color(255, 209, 209));
        custom_JPanelGradient1.setColorStart(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout custom_JPanelGradient1Layout = new javax.swing.GroupLayout(custom_JPanelGradient1);
        custom_JPanelGradient1.setLayout(custom_JPanelGradient1Layout);
        custom_JPanelGradient1Layout.setHorizontalGroup(
            custom_JPanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1066, Short.MAX_VALUE)
        );
        custom_JPanelGradient1Layout.setVerticalGroup(
            custom_JPanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pn_kanan.add(custom_JPanelGradient1, java.awt.BorderLayout.PAGE_START);

        pn_dasar.setBackground(new java.awt.Color(250, 250, 250));

        pn_utama.setBackground(new java.awt.Color(255, 255, 255));
        pn_utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pn_dasarLayout = new javax.swing.GroupLayout(pn_dasar);
        pn_dasar.setLayout(pn_dasarLayout);
        pn_dasarLayout.setHorizontalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        pn_dasarLayout.setVerticalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pn_kanan.add(pn_dasar, java.awt.BorderLayout.CENTER);

        getContentPane().add(pn_kanan, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void btn_lpPenangananMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lpPenangananMouseExited
        pn_btnlpPenanganan.setBackground(new Color(255, 255, 255));
        pn_line12.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_lpPenangananMouseExited

    private void btn_lpPenangananMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lpPenangananMouseEntered
        pn_btnlpPenanganan.setBackground(new Color(250, 250, 250));
        pn_line12.setBackground(new Color(246, 127, 127));
    }//GEN-LAST:event_btn_lpPenangananMouseEntered

    private void btn_lpPenangananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lpPenangananMouseClicked
        pn_btnlpPenanganan.setBackground(new Color(240, 240, 240));
        pn_line12.setBackground(new Color(246, 127, 127));
        
       pn_utama.removeAll();
        pn_utama.add(new cetak_faktur_Penanganan());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_lpPenangananMouseClicked

    private void btn_lpPenerimaanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lpPenerimaanMouseExited
        pn_btnlpPenerimaan.setBackground(new Color(255, 255, 255));
        pn_line11.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_lpPenerimaanMouseExited

    private void btn_lpPenerimaanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lpPenerimaanMouseEntered
        pn_btnlpPenerimaan.setBackground(new Color(250, 250, 250));
        pn_line11.setBackground(new Color(246, 127, 127));
    }//GEN-LAST:event_btn_lpPenerimaanMouseEntered

    private void btn_lpPenerimaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lpPenerimaanMouseClicked
        pn_btnlpPenerimaan.setBackground(new Color(240, 240, 240));
        pn_line11.setBackground(new Color(246, 127, 127));
        
        pn_utama.removeAll();
        pn_utama.add(new cetak_faktur_Penerimaan());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_lpPenerimaanMouseClicked

    private void btn_lpAmbulanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lpAmbulanMouseExited
        pn_btnlpAmbulan.setBackground(new Color(255, 255, 255));
        pn_line10.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_lpAmbulanMouseExited

    private void btn_lpAmbulanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lpAmbulanMouseEntered
        pn_btnlpAmbulan.setBackground(new Color(250, 250, 250));
        pn_line10.setBackground(new Color(246, 127, 127));
    }//GEN-LAST:event_btn_lpAmbulanMouseEntered

    private void btn_lpAmbulanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lpAmbulanMouseClicked
        pn_btnlpAmbulan.setBackground(new Color(240, 240, 240));
        pn_line10.setBackground(new Color(246, 127, 127));
        
        pn_utama.removeAll();
        pn_utama.add(new cetak_faktur_Ambulan());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_lpAmbulanMouseClicked

    private void btn_lpPetugasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lpPetugasMouseExited
        pn_btnlpKegiatan.setBackground(new Color(255, 255, 255));
        pn_line9.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_lpPetugasMouseExited

    private void btn_lpPetugasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lpPetugasMouseEntered
        pn_btnlpKegiatan.setBackground(new Color(250, 250, 250));
        pn_line9.setBackground(new Color(246, 127, 127));
    }//GEN-LAST:event_btn_lpPetugasMouseEntered

    private void btn_lpPetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lpPetugasMouseClicked
        pn_btnlpKegiatan.setBackground(new Color(240, 240, 240));
        pn_line9.setBackground(new Color(246, 127, 127));
        
         pn_utama.removeAll();
        pn_utama.add(new cetak_faktur_Petugas());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_lpPetugasMouseClicked

    private void btn_lpPasienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lpPasienMouseExited
        pn_btnlpAnggota.setBackground(new Color(255, 255, 255));
        pn_line8.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_lpPasienMouseExited

    private void btn_lpPasienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lpPasienMouseEntered
        pn_btnlpAnggota.setBackground(new Color(250, 250, 250));
        pn_line8.setBackground(new Color(246, 127, 127));
    }//GEN-LAST:event_btn_lpPasienMouseEntered

    private void btn_lpPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lpPasienMouseClicked
        pn_btnlpAnggota.setBackground(new Color(240, 240, 240));
        pn_line8.setBackground(new Color(246, 127, 127));
        
        pn_utama.removeAll();
        pn_utama.add(new cetak_faktur_Pasien());
        pn_utama.repaint();
        pn_utama.revalidate();
        
    }//GEN-LAST:event_btn_lpPasienMouseClicked

    private void btn_penangananMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_penangananMouseExited
        pn_btnPenanganan.setBackground(new Color(255, 255, 255));
        pn_line7.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_penangananMouseExited

    private void btn_penangananMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_penangananMouseEntered
        pn_btnPenanganan.setBackground(new Color(250, 250, 250));
        pn_line7.setBackground(new Color(246, 127, 127));
    }//GEN-LAST:event_btn_penangananMouseEntered

    private void btn_penangananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_penangananMouseClicked
        pn_btnPenanganan.setBackground(new Color(240, 240, 240));
        pn_line7.setBackground(new Color(246, 127, 127));
        
        pn_utama.removeAll();
        pn_utama.add(new Menu_Penanganan());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_penangananMouseClicked

    private void btn_penerimaanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_penerimaanMouseExited
        pn_btnPenerimaan.setBackground(new Color(255, 255, 255));
        pn_line6.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_penerimaanMouseExited

    private void btn_penerimaanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_penerimaanMouseEntered
        pn_btnPenerimaan.setBackground(new Color(250, 250, 250));
        pn_line6.setBackground(new Color(246, 127, 127));
    }//GEN-LAST:event_btn_penerimaanMouseEntered

    private void btn_penerimaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_penerimaanMouseClicked
        pn_btnPenerimaan.setBackground(new Color(240, 240, 240));
        pn_line6.setBackground(new Color(246, 127, 127));
        
        pn_utama.removeAll();
        pn_utama.add(new Menu_Penerimaan());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_penerimaanMouseClicked

    private void btn_ambulanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ambulanMouseExited
        pn_btnAmbulan.setBackground(new Color(255, 255, 255));
        pn_line5.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_ambulanMouseExited

    private void btn_ambulanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ambulanMouseEntered
        pn_btnAmbulan.setBackground(new Color(250, 250, 250));
        pn_line5.setBackground(new Color(246, 127, 127));
    }//GEN-LAST:event_btn_ambulanMouseEntered

    private void btn_ambulanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ambulanMouseClicked
        pn_btnAmbulan.setBackground(new Color(240, 240, 240));
        pn_line5.setBackground(new Color(246, 127, 127));
        
        pn_utama.removeAll();
        pn_utama.add(new Menu_Ambulans());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_ambulanMouseClicked

    private void btn_petugasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_petugasMouseExited
        pn_btnPetugas.setBackground(new Color(255, 255, 255));
        pn_line4.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_petugasMouseExited

    private void btn_petugasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_petugasMouseEntered
        pn_btnPetugas.setBackground(new Color(250, 250, 250));
        pn_line4.setBackground(new Color(246, 127, 127));
    }//GEN-LAST:event_btn_petugasMouseEntered

    private void btn_petugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_petugasMouseClicked
        pn_btnPetugas.setBackground(new Color(240, 240, 240));
        pn_line4.setBackground(new Color(246, 127, 127));
        
        pn_utama.removeAll();
        pn_utama.add(new Menu_Petugas());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_petugasMouseClicked

    private void btn_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseExited
        pn_btnDashboard.setBackground(new Color(255, 255, 255));
        pn_line.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_dashboardMouseExited

    private void btn_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseEntered
        pn_btnDashboard.setBackground(new Color(250, 250, 250));
        pn_line.setBackground(new Color(246, 127, 127));
    }//GEN-LAST:event_btn_dashboardMouseEntered

    private void btn_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseClicked
        pn_btnDashboard.setBackground(new Color(240, 240, 240));
        pn_line.setBackground(new Color(246, 127, 127));

        pn_utama.removeAll();
        pn_utama.add(new Menu_Dashboard());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_dashboardMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        pn_utama.removeAll();
        pn_utama.add(new Menu_Dashboard());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_formWindowOpened

    private void btn_pasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pasienMouseClicked
        pn_btnPasien.setBackground(new Color(240, 240, 240));
        pn_line3.setBackground(new Color(246, 127, 127));
        
        pn_utama.removeAll();
        pn_utama.add(new Menu_Pasien());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_pasienMouseClicked

    private void btn_pasienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pasienMouseEntered
        pn_btnPasien.setBackground(new Color(250, 250, 250));
        pn_line3.setBackground(new Color(246, 127, 127));
    }//GEN-LAST:event_btn_pasienMouseEntered

    private void btn_pasienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pasienMouseExited
        pn_btnPasien.setBackground(new Color(255, 255, 255));
        pn_line3.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_pasienMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_ambulan;
    private javax.swing.JLabel btn_dashboard;
    private javax.swing.JLabel btn_lpAmbulan;
    private javax.swing.JLabel btn_lpPasien;
    private javax.swing.JLabel btn_lpPenanganan;
    private javax.swing.JLabel btn_lpPenerimaan;
    private javax.swing.JLabel btn_lpPetugas;
    private javax.swing.JLabel btn_pasien;
    private javax.swing.JLabel btn_penanganan;
    private javax.swing.JLabel btn_penerimaan;
    private javax.swing.JLabel btn_petugas;
    private Custom.Custom_JPanelGradient custom_JPanelGradient1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pn_btnAmbulan;
    private javax.swing.JPanel pn_btnDashboard;
    private javax.swing.JPanel pn_btnPasien;
    private javax.swing.JPanel pn_btnPenanganan;
    private javax.swing.JPanel pn_btnPenerimaan;
    private javax.swing.JPanel pn_btnPetugas;
    private javax.swing.JPanel pn_btnlpAmbulan;
    private javax.swing.JPanel pn_btnlpAnggota;
    private javax.swing.JPanel pn_btnlpKegiatan;
    private javax.swing.JPanel pn_btnlpPenanganan;
    private javax.swing.JPanel pn_btnlpPenerimaan;
    private javax.swing.JPanel pn_dasar;
    private javax.swing.JPanel pn_kanan;
    private javax.swing.JPanel pn_kiri;
    private javax.swing.JPanel pn_line;
    private javax.swing.JPanel pn_line10;
    private javax.swing.JPanel pn_line11;
    private javax.swing.JPanel pn_line12;
    private javax.swing.JPanel pn_line3;
    private javax.swing.JPanel pn_line4;
    private javax.swing.JPanel pn_line5;
    private javax.swing.JPanel pn_line6;
    private javax.swing.JPanel pn_line7;
    private javax.swing.JPanel pn_line8;
    private javax.swing.JPanel pn_line9;
    private javax.swing.JPanel pn_utama;
    // End of variables declaration//GEN-END:variables
}
